apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-hpa
spec:
  # HPA будет скейлить количество подов в зависимости от утилизации CPU. Здесь считаем, что если утилизация выше 50% от запрошенных 500m, поды скейлятся до 5 штук, чтобы обработать входящую нагрузку
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
